# Generated by Django 3.2.7 on 2021-10-02 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(max_length=5)),
                ('avalmobudget', models.IntegerField(help_text='Enter your available monthly budget.', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Debts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.IntegerField(help_text='Enter the principal amount for this debt.', max_length=6)),
                ('interest', models.IntegerField(help_text='Enter the interest rate for this debt.', max_length=3)),
                ('minmopmt', models.IntegerField(help_text='Enter the minimum monthly payment required for this debt.', max_length=4)),
                ('recmopmt', models.IntegerField(max_length=5, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snowballapp.users', verbose_name='users')),
            ],
        ),
    ]
