# Generated by Django 3.2.7 on 2021-10-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowballapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debts',
            name='interest',
            field=models.IntegerField(help_text='Enter the interest rate for this debt.'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='minmopmt',
            field=models.IntegerField(help_text='Enter the minimum monthly payment required for this debt.'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='principal',
            field=models.IntegerField(help_text='Enter the principal amount for this debt.'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='recmopmt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='avalmobudget',
            field=models.IntegerField(help_text='Enter your available monthly budget.'),
        ),
        migrations.AlterField(
            model_name='users',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
