# Generated by Django 3.2.7 on 2021-10-02 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snowballapp', '0002_auto_20211002_0307'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UsersModel',
        ),
        migrations.DeleteModel(
            name='Debts',
        ),
    ]
