# Generated by Django 3.2.7 on 2021-10-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowballapp', '0003_auto_20211002_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersmodel',
            name='userid',
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='interestrate',
            field=models.IntegerField(help_text='Enter the interest rate for this debt.', null=True),
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='minmopmt',
            field=models.IntegerField(help_text='Enter the minimum monthly payment required for this debt.', null=True),
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='principal',
            field=models.IntegerField(help_text='Enter the principal amount for this debt.', null=True),
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='recmopmt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='avalmobudget',
            field=models.IntegerField(help_text='Enter your available monthly budget.', null=True),
        ),
    ]
