# Generated by Django 3.2.7 on 2021-10-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowballapp', '0004_auto_20211002_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersmodel',
            name='username',
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='avalmobudget',
            field=models.IntegerField(help_text=' ', null=True),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='interestrate',
            field=models.IntegerField(help_text=' ', null=True),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='minmopmt',
            field=models.IntegerField(help_text=' ', null=True),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='principal',
            field=models.IntegerField(help_text=' ', null=True),
        ),
    ]
