# Generated by Django 3.2.7 on 2021-10-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowballapp', '0006_remove_usersmodel_recmopmt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersmodel',
            old_name='avalmobudget',
            new_name='AvailableMonthlyBudget',
        ),
        migrations.RenameField(
            model_name='usersmodel',
            old_name='interestrate',
            new_name='InterestRate',
        ),
        migrations.RenameField(
            model_name='usersmodel',
            old_name='principal',
            new_name='Principal',
        ),
        migrations.RemoveField(
            model_name='usersmodel',
            name='minmopmt',
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='MinimumMonthlyPayment',
            field=models.IntegerField(help_text='Minimum Monthly Payment', null=True),
        ),
    ]
